# This workflow will do a clean installation of node dependencies, cache/restore them and build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Goal Management CD

env:
  REACT_APP_KEYCLOAK_URL: ${{ secrets.prod.REACT_APP_KEYCLOAK_URL }}
  REACT_APP_KEYCLOAK_REALM: ${{ secrets.prod.REACT_APP_KEYCLOAK_REALM }}
  REACT_APP_KEYCLOAK_CLIENT_ID: ${{ secrets.prod.REACT_APP_KEYCLOAK_CLIENT_ID }}

on:
  push:
    branches:
      - GM-8-Deploy_front_end_application

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install npm dependencies
      run: npm i

    - name: Build app
      run: |
        echo URL: ${{ env.REACT_APP_KEYCLOAK_URL }}
        npm run build
